# Generated by Django 4.0.5 on 2022-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
    ]
